[[redirects]]
  from = "/2019/*"
  to = "https://archive.distributedsql.org/2019/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/OGImage.png"
  to = "/dss-asia-2022.png"
  status = 200
  force = true
